export const CAPABILITIES = [
  { icon: '📊', name: 'Dashboard',                desc: 'Portfolio overview, P&L, holdings, and live prices.' },
  { icon: '📈', name: 'Performance',              desc: 'FIFO returns, EUR/USD handling, vs S&P 500 mirror.' },
  { icon: '🧠', name: 'AI Research',              desc: 'Bull/bear case per holding, generated by Claude.' },
  { icon: '📅', name: 'Earnings',                 desc: 'Beat/miss history, EPS estimates, calendar.' },
  { icon: '🎯', name: 'Analyst Ratings',          desc: 'Price targets, consensus, recent revisions.' },
  { icon: '👤', name: 'Insider Transactions',     desc: 'Officer + director buys and sells, last 30 days.' },
  { icon: '🏦', name: 'Institutional Ownership',  desc: '13F filings, hedge fund moves, top holders.' },
  { icon: '📉', name: 'Short Interest',           desc: 'Float, days to cover, and short trends.' },
  { icon: '⚖️', name: 'Valuation',                desc: 'P/E, P/S, P/FCF, and peer-group comparisons.' },
  { icon: '🌐', name: 'Macro',                    desc: 'VIX, rates, market pulse — context for every trade.' },
];
