export const CAPABILITIES = [
  { icon: '📊', name: 'Dashboard',                desc: 'Portfolio overview, P&L, holdings, and live prices.',        href: '/dashboard' },
  { icon: '📈', name: 'Performance',              desc: 'FIFO returns, EUR/USD handling, vs S&P 500 mirror.',          href: '/performance' },
  { icon: '🧠', name: 'AI Research',              desc: 'Bull/bear case per holding, generated by Claude.',            href: '/research' },
  { icon: '📅', name: 'Earnings',                 desc: 'Beat/miss history, EPS estimates, calendar.',                 href: '/earnings' },
  { icon: '🎯', name: 'Analyst Ratings',          desc: 'Price targets, consensus, recent revisions.',                 href: '/ratings-and-shorts' },
  { icon: '👤', name: 'Insider Transactions',     desc: 'Officer + director buys and sells, last 30 days.',            href: '/insider' },
  { icon: '🏦', name: 'Institutional Ownership',  desc: '13F filings, hedge fund moves, top holders.',                 href: '/ownership' },
  { icon: '📉', name: 'Short Interest',           desc: 'Float, days to cover, and short trends.',                     href: '/ratings-and-shorts' },
  { icon: '⚖️', name: 'Valuation',                desc: 'P/E, P/S, P/FCF, and peer-group comparisons.',                href: '/valuation' },
  { icon: '🌐', name: 'Macro',                    desc: 'VIX, rates, market pulse — context for every trade.',         href: '/macro' },
];
